name: CI/CD Pipeline credit-portal

# Trigger the pipeline only when a push is made to the main branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy the already built Sam Image for upload
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout Current Commit.
        uses: actions/checkout@v3 

      - name: Setup Sam
        if: ${{ hashFiles('.aws-sam') != '' }}
        uses: aws-actions/setup-sam@v2
      
      - name: Setup AWS Credentials
        if: ${{ hashFiles('.aws-sam') != '' }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Sam Deploy Image
        if: ${{ hashFiles('.aws-sam') != '' }}
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset